# Generated by Django 5.2 on 2025-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_ficheconsultation_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheconsultation',
            name='lieu_medicaments',
        ),
        migrations.RemoveField(
            model_name='ficheconsultation',
            name='present',
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='autre',
            field=models.BooleanField(default=False, help_text='Un autre intervenant est-il présent ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='centre_sante_medicaments',
            field=models.BooleanField(default=False, help_text='Des médicaments sont-ils pris au centre de santé ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='hopital_medicaments',
            field=models.BooleanField(default=False, help_text="Des médicaments sont-ils pris à l'hôpital ?"),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='maison_medicaments',
            field=models.BooleanField(default=False, help_text='Des médicaments sont-ils pris à la maison ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='medecin',
            field=models.BooleanField(default=False, help_text='Un médecin est-il présent ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='medicaments_non_pris',
            field=models.BooleanField(default=False, help_text="Des médicaments n'ont-ils pas été pris ?"),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='patient',
            field=models.BooleanField(default=True, help_text='Le patient est-il présent ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='pharmacie_medicaments',
            field=models.BooleanField(default=False, help_text='Des médicaments sont-ils pris à la pharmacie ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='proche',
            field=models.BooleanField(default=False, help_text='Un proche est-il présent ?'),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='soignant',
            field=models.BooleanField(default=False, help_text='Un soignant est-il présent ?'),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='cephalees',
            field=models.BooleanField(blank=True, default=False, help_text='Le patient a-t-il des céphalées ?', null=True),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='nycturie',
            field=models.BooleanField(blank=True, default=False, help_text='Le patient a-t-il des nycturies ?', null=True),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='palpitations',
            field=models.BooleanField(blank=True, default=False, help_text='Le patient a-t-il des palpitations ?', null=True),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='troubles_visuels',
            field=models.BooleanField(blank=True, default=False, help_text='Le patient a-t-il des troubles visuels ?', null=True),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='vertiges',
            field=models.BooleanField(blank=True, default=False, help_text='Le patient a-t-il des vertiges ?', null=True),
        ),
    ]
