# Generated by Django 4.2.23 on 2025-06-12 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='commentaire_medecin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='is_patient_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='medecin_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='status',
            field=models.CharField(choices=[('en_analyse', "En cours d'analyse"), ('analyse_terminee', 'Analyse terminée'), ('valide_medecin', 'Validé par médecin'), ('rejete_medecin', 'Rejeté par médecin')], default='en_analyse', max_length=20),
        ),
    ]
