# Generated by Django 4.2.23 on 2025-06-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_ficheconsultation_commentaire_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='diagnostic_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
