# Generated by Django 4.2.24 on 2025-09-11 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='assigned_medecin',
            field=models.ForeignKey(blank=True, help_text='Médecin assigné pour le suivi de la consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FicheMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_messages', to=settings.AUTH_USER_MODEL)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.ficheconsultation')),
            ],
            options={
                'verbose_name': 'Message Fiche',
                'verbose_name_plural': 'Messages Fiche',
                'ordering': ['created_at'],
            },
        ),
    ]
