# Generated by Django 4.2.23 on 2025-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_ficheconsultation_diagnostic_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10),
        ),
    ]
