# Generated by Django 4.2.23 on 2025-10-03 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_ficheconsultation_assigned_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_mode',
            field=models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel/Téléconsultation')], default='distanciel', help_text='Mode de consultation', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location_note',
            field=models.TextField(blank=True, help_text='Adresse ou informations de connexion selon le mode', null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='analyses_proposees',
            field=models.TextField(blank=True, help_text='Analyses paracliniques que vous proposez', null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='hypothese_patient_medecin',
            field=models.TextField(blank=True, help_text='À quoi pensez-vous ? Hypothèse diagnostique du patient ou médecin', null=True),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='coloration_bulbaire',
            field=models.CharField(choices=[('normale', 'Normale'), ('jaunatre', 'Jaunâtre'), ('rougeatre', 'Rougeâtre')], default='normale', max_length=20),
        ),
        migrations.AlterField(
            model_name='ficheconsultation',
            name='coloration_palpebrale',
            field=models.CharField(choices=[('normale', 'Normale'), ('pale', 'Pâle')], default='normale', max_length=20),
        ),
        migrations.CreateModel(
            name='MedecinException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text="Début de l'exception")),
                ('end_datetime', models.DateTimeField(help_text="Fin de l'exception")),
                ('exception_type', models.CharField(choices=[('unavailable', 'Indisponible'), ('busy', 'Occupé'), ('vacation', 'Congé'), ('formation', 'Formation'), ('emergency', 'Urgence')], default='unavailable', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Raison de l'indisponibilité", null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='Exception récurrente (chaque semaine)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exception Médecin',
                'verbose_name_plural': 'Exceptions Médecin',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyse', models.CharField(help_text="Type d'analyse (ex: Glycémie, Hémoglobine, Créatinine, etc.)", max_length=100)),
                ('valeur', models.CharField(help_text='Valeur du résultat', max_length=50)),
                ('unite', models.CharField(blank=True, help_text='Unité de mesure', max_length=20, null=True)),
                ('valeurs_normales', models.CharField(blank=True, help_text='Plage de valeurs normales', max_length=100, null=True)),
                ('date_prelevement', models.DateField(help_text='Date du prélèvement')),
                ('laboratoire', models.CharField(blank=True, help_text='Nom du laboratoire', max_length=255, null=True)),
                ('fichier', models.FileField(blank=True, help_text='Fichier PDF/image du résultat', null=True, upload_to='lab_results/')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire du laboratoire', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='chat.ficheconsultation')),
            ],
            options={
                'verbose_name': 'Résultat de Laboratoire',
                'verbose_name_plural': 'Résultats de Laboratoire',
                'ordering': ['-date_prelevement', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FicheReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre de la référence', max_length=255)),
                ('url', models.URLField(blank=True, help_text='URL de la référence', null=True)),
                ('source', models.CharField(choices=[('pubmed', 'PubMed'), ('cinahl', 'CINAHL'), ('has', 'HAS (Haute Autorité de Santé)'), ('cochrane', 'Cochrane'), ('other', 'Autre')], default='other', help_text='Source de la référence', max_length=50)),
                ('authors', models.CharField(blank=True, help_text='Auteurs', max_length=500, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Année de publication', null=True)),
                ('journal', models.CharField(blank=True, help_text='Journal/Revue', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='chat.ficheconsultation')),
            ],
            options={
                'verbose_name': 'Référence Fiche',
                'verbose_name_plural': 'Références Fiche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FicheAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Fichier joint', upload_to='attachments/%Y/%m/')),
                ('kind', models.CharField(choices=[('image', 'Image/Photo'), ('document', 'Document'), ('xray', 'Radiographie'), ('scan', 'Scanner/IRM'), ('prescription', 'Ordonnance'), ('other', 'Autre')], default='other', help_text='Type de pièce jointe', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Description/note sur le fichier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.ficheconsultation')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('parquet', 'Parquet'), ('json', 'JSON'), ('excel', 'Excel')], default='csv', max_length=20)),
                ('date_start', models.DateField(help_text="Date de début pour l'export")),
                ('date_end', models.DateField(help_text="Date de fin pour l'export")),
                ('include_personal_data', models.BooleanField(default=False, help_text='Inclure les données personnelles (nom, téléphone, etc.)')),
                ('filters', models.JSONField(default=dict, help_text='Filtres appliqués (status, age_range, etc.)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Chemin du fichier généré', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Taille du fichier en bytes', null=True)),
                ('records_count', models.IntegerField(blank=True, help_text="Nombre d'enregistrements exportés", null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec", null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Export Données',
                'verbose_name_plural': 'Jobs Export Données',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('whatsapp_incoming', 'WhatsApp Entrant'), ('sms_incoming', 'SMS Entrant'), ('whatsapp_status', 'Statut WhatsApp'), ('sms_status', 'Statut SMS')], max_length=30)),
                ('external_id', models.CharField(help_text='ID externe du message (Twilio SID, etc.)', max_length=255)),
                ('sender_phone', models.CharField(help_text='Numéro de téléphone expéditeur', max_length=30)),
                ('recipient_phone', models.CharField(help_text='Numéro de téléphone destinataire', max_length=30)),
                ('content', models.TextField(help_text='Contenu du message')),
                ('raw_payload', models.JSONField(help_text='Payload brut du webhook')),
                ('processing_status', models.CharField(choices=[('pending', 'En attente'), ('processed', 'Traité'), ('failed', 'Échec'), ('ignored', 'Ignoré')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Erreur de traitement', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_message', models.ForeignKey(blank=True, help_text='Message créé suite au webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.fichemessage')),
                ('related_fiche', models.ForeignKey(blank=True, help_text='Fiche associée (si trouvée)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.ficheconsultation')),
                ('related_user', models.ForeignKey(blank=True, help_text='Utilisateur associé (si trouvé)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement Webhook',
                'verbose_name_plural': 'Événements Webhook',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['sender_phone'], name='chat_webhoo_sender__bc7284_idx'), models.Index(fields=['external_id'], name='chat_webhoo_externa_8741d6_idx'), models.Index(fields=['processing_status'], name='chat_webhoo_process_da1482_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedecinAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0=Lundi, 6=Dimanche)')),
                ('start_time', models.TimeField(help_text='Heure de début du créneau')),
                ('end_time', models.TimeField(help_text='Heure de fin du créneau')),
                ('consultation_type', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('both', 'Les deux')], default='both', help_text='Type de consultation accepté', max_length=20)),
                ('duration_minutes', models.IntegerField(default=30, help_text="Durée d'une consultation en minutes")),
                ('is_active', models.BooleanField(default=True, help_text='Créneau actif')),
                ('max_consultations', models.IntegerField(default=1, help_text='Nombre maximum de consultations sur ce créneau')),
                ('location', models.CharField(blank=True, help_text='Lieu pour consultations présentielles', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes privées du médecin sur ce créneau', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité Médecin',
                'verbose_name_plural': 'Disponibilités Médecin',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('medecin', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
