# Generated by Django 4.2.23 on 2025-10-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_p0_p1_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheconsultation',
            name='signature_medecin',
            field=models.FileField(blank=True, help_text='Signature du médecin pour valider la consultation', null=True, upload_to='signatures/'),
        ),
    ]
