# Generated by Django 4.2.23 on 2025-06-16 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_ficheconsultation_sexe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheconsultation',
            name='sexe',
        ),
        migrations.AddField(
            model_name='conversation',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.ficheconsultation'),
        ),
        migrations.AlterField(
            model_name='messageia',
            name='role',
            field=models.CharField(max_length=32),
        ),
    ]
