# Generated by Django 4.2.23 on 2026-01-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_ficheconsultation_signature_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='nom_hopital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
