# Generated by Django 4.2.23 on 2025-06-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_ficheconsultation_sexe_conversation_fiche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheconsultation',
            name='conversation',
        ),
        migrations.AlterField(
            model_name='messageia',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='messageia',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('gpt4', 'GPT-4'), ('claude', 'Claude 3'), ('gemini', 'Gemini Pro'), ('synthese', 'Synthèse Finale')], max_length=20),
        ),
    ]
