# Generated by Django 5.2 on 2025-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_ficheconsultation_conversation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='ficheconsultation',
            options={'ordering': ['-date_consultation'], 'verbose_name': 'Fiche de Consultation', 'verbose_name_plural': 'Fiches de Consultation'},
        ),
        migrations.AlterModelOptions(
            name='messageia',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message IA', 'verbose_name_plural': 'Messages IA'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
