# Generated by Django 5.2 on 2025-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficheconsultation',
            old_name='commentaire_medecin',
            new_name='diagnostic',
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='examen_complementaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='recommandations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficheconsultation',
            name='traitement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
