# Generated by Django 5.2 on 2025-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_rename_commentaire_medecin_ficheconsultation_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheconsultation',
            name='signature_medecin',
            field=models.ImageField(blank=True, help_text='Signature du médecin pour valider la consultation', null=True, upload_to='signatures/'),
        ),
    ]
