# Generated by Django 5.2 on 2025-07-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_ficheconsultation_signature_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
