# Generated by Django 4.2.24 on 2025-09-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemedecin',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Le médecin est-il disponible pour de nouveaux patients ?'),
        ),
    ]
